#TODO
#ADD ARROW 
#SHOW USER HOW OT GET RAPID API KEY


aseURL: https://bespokediets.com
languageCode: en-us
title: Bespoke Diet Generator API
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/navbar-logo.png
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Bespoke Diet Generator 
    # Hero subtitle (optional)
    subtitle: We are solving the complexity of generating personalized diets so you can add them to any web or mobile applications. Give it a try by generating a diet now for free!   
    text:
    # Button text
    buttontext: Go to RapidAPI
    # Where the main hero button links to
    buttonlink: https://rapidapi.com/genez-io-genez-io-default/api/bespoke-diet-generator/
    tutbuttontext: Tutorials
    # Where the main hero button links to
    tutbuttonlink: /#tutorials
    # Hero image (from static/images/___)
    image: illustrations/main.jpg

  section2: 
    title: Features
    features:
    - title: Simple, effective, precise 
      text: Use a simple API to generate an effective diet using precise quantities from selected ingredients.
      icon: simple
    - title: Ingredient replacement calculator 
      text: Offer flexibility and adaptibility to your users by allowing them to change ingredients in an already generated diet.
      # TODO: add out icon and change text above
      icon: switch
    - title: Generate diets that work
      text: The generated diets are easy to follow, because we offer the choice of eliminating undesired food items.
      # TODO: add out icon and change text above
      icon: diet

  getstarted:
    title: Get started with our diet generator API

    features:
      - number: 1
        step: Obtain an App Key from RapidAPI.
      - number: 2
        step: Create a user and set its biometrics data using POST.
      - number: 3
        step: Set the ingredients that the user does not like.
      - number: 4
        step: Generate the diet!
      - number: 5
        step: Change ingredients from the newly generated diet to match better user’s preferences.
    image: illustrations/second.jpg

  tutorials:
    title: Tutorials
    clients:
    - name: Part 1
      description: How to generate your own diets using NodeJS
      url: /how-to-generate-your-own-diets-using-nodejs
    - name: Part 2
      description: How to configure the diet and replace ingredients
      url: /how-to-configure-the-diet-and-replace-ingredients
    - name: Part 3
      description: How to handle errors
      url: /how-to-handle-errors


  section4:
    title: API Users
    clients:
    - name: Crave Nutrition
      description: Personalized diets and meal plans to cover all food preferences, gentle fitness programs and nutritionist support, all in one place.
      img: crave_logo
      url: https://apps.apple.com/us/app/crave-bespoke-nutrition/id1581722434
    - name: Yummdiet
      description: With the help of algorithms we calculate and customize your nutritional plan according to your food preferences, your lifestyle and your individual data.
      img: yumm_logo
      url: https://yummdiet.com/

  section1:
    title: Pricing
    tiles:
    - title: Basic
      subtitle: $0.00
      icon: mouse-globe
      limit1: 100
      limit_type1: Hard Limit
      limit2: 100
      limit_type2: Hard Limit
      limit3: 10,000
      limit_type3: Hard Limit
      limit4: 1,000
      limit_type4: Hard Limit
      url: https://rapidapi.com/genez-io-genez-io-default/api/bespoke-diet-generator
      buttonText: Subscribe
    - title: Pro
      subtitle: $14.90
      limit1: 100
      limit_type1: (+$0.2 each other)
      limit2: 100
      limit_type2: (+$0.2 each other)
      limit3: 10,000
      limit_type3: (+$0.002 each other)
      limit4: Unlimited
      url: https://rapidapi.com/genez-io-genez-io-default/api/bespoke-diet-generator
      buttonText: Subscribe
    - title: Ultra
      subtitle: $49.90
      limit1: 1,000
      limit_type1: (+$0.2 each other)
      limit2: 1,000
      limit_type2: (+$0.2 each other)
      limit3: 100,000
      limit_type3: (+$0.002 each other)
      limit4: Unlimited
      recommended: Recommended
      url: https://rapidapi.com/genez-io-genez-io-default/api/bespoke-diet-generator
      buttonText: Subscribe

  section5: true
      

  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Home
    url: /#hero
  - title: Features
    url: /#features
  - title: Pricing
    url: /#pricing
  - title: Documentation
    url: /documentation
  - title: Tutorials
    url: /#tutorials
  - title: Contact
    url: /#contact
  
  
  footer:
    # Logo (from /images/logos/___)
    logo: White-logo-no-background.svg
    # Social Media Title
    socialmediatitle: Follow Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://github.com/Genez-io
      icon: github
    - link: https://www.linkedin.com/company/simplecapital/
      icon: linkedin
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /#features
        - text: Pricing
          link: /#pricing
        - text: Documentation
          link: /documentation
        - text: Tutorials
          link: /#tutorials
